### ISSUE TITLE
[The Magic Highlighter] background color makes text hard to read

### ISSUE THREAD

**Issue by calebhailey** [herdworks/feedback#4]
### Product

The Magic Highlighter

### Subject

Background color and text are the same color / hard to read 

### Feedback

I noticed a bug/unintended side effect of having Magic Highlighter turned on. I’m not sure if this is a more widespread issue, but on the CSS-Tricks website Magic Highlighter hides the background behind the article titles and subtitles, making the white text invisible. Just thought I’d give you a heads up in case it’s fixable! Here’s an example url, and I’ve attached screenshots:

https://css-tricks.com/snippets/css/complete-guide-grid/

### Context

![5B9FECC6-F105-4893-BF95-E9BD873CB6F5](https://user-images.githubusercontent.com/141373/219174119-f24e06c0-3d37-4dd0-9f0f-09e54aca1c3d.jpeg)

![CFCC5424-C289-42A1-9572-1418DFE4115C](https://user-images.githubusercontent.com/141373/219174161-2ed4b3ba-96eb-4425-b131-9583bf082067.jpeg)

This feedback was submitted via Mastodon.

References: 

* https://hachyderm.io/@Timdmackey/109870025917295335

### Code of Conduct

- [X] I have read and agree to the Herd Works Product Feedback Issue Tracker project's [Code of Conduct](https://github.com/herdworks/feedback/blob/main/CODE_OF_CONDUCT.md)

### Tasks 

- [x] herdworks/magichighlighter-app#35

**Comment by calebhailey** [comment]
Here's a fun screenshot that really, er, _highlights_ the problem. 🤓 

<img width="1624" alt="CleanShot 2023-02-15 at 14 43 09@2x" src="https://user-images.githubusercontent.com/141373/219205081-eace6aa2-2e11-4cbf-bba0-8edb4046adb7.png">

**Comment by timdmackey** [comment]
Similar issue here, I'm unsure if the cause is the same though. In this case, Magic Highlighter is interacting with another browser extension ["Noir"](https://getnoir.app) to produce very difficult to read text. Noir is an extension that simulated dark mode on websites which don't have a dark theme.

In this case it appears that Noir is applying a dark background to the webpage along with light grey text, and Magic Highlighter is then reverting the background to white, resulting in difficult-to-read light grey text on white. 

Here's an example url: https://variety.com/2023/film/columns/leslie-grace-batgirl-canceled-interview-dc-studios-1235519751/

![image](https://user-images.githubusercontent.com/182772/219265692-d09c9bbf-8e6d-4251-b59c-10fbfcc6e55b.png)

**Comment by timdmackey** [comment]
Another report of the same issue: https://techhub.social/@chrisdreiling/109869722259610874

"@calebhailey@mastodon.social The Magic Highlighter is so cool, but I’m noticing that it isn’t playing well with my dark mode extension (Noir.) I’ve attached a couple of screenshots showing the issue, and turning off Magic Highlighter makes the pages render correctly. Just wanted to bring that to your attention, keep up the great work!"

![image](https://user-images.githubusercontent.com/182772/219266025-1c1f9ee3-4700-4e25-8fb1-745a468ace6c.jpeg)

![image](https://user-images.githubusercontent.com/182772/219266033-355068e6-5aac-4883-a922-23141ae1d7d6.jpeg)

**Comment by calebhailey** [comment]
Released in 0.5.2
